#!/usr/bin/env bash
# configuration of new server with the help of 'sed' command
# +We first update the packages
# +Secondwe installing nginx
# +Using sed command insert a new header
# +Finally restarting ngnix
apt-get -y update
apt-get -y install nginx
sudo sed -i "listen 80 default_server;/a add_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default
service nginx restart
