#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
#!/bin/bash
PASSWORD=$1
DATE=$(date +%d-%m-%Y)
mysqldump -u root -p${PASSWORD} --all-databases > backup.sql
tar -czvf $DATE.tar.gz backup.sql
