#!/usr/bin/env bash
# configures /etc/nginx/sites-enabled/default file from 8080 to 80:
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
