#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

i=0
while [ $i -le 12 ]
do
	echo "Hour: $i"
	j=0
	while [ $j -le 59 ]
	do
		echo "&j"
		((j++))
	done
	((i++))
done
