#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01
sudo apt-get install ufw
sudo ufw enable
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
sudo ufw default deny incoming
