#!/usr/bin/env bash
# running nignx not as the root user, rather as the nginx user, and all requests would be litsened via port 8080
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
